pipeline:
  identifier: Build_terraform_configs_1684507170680
  name: Build terraform-configs
  orgIdentifier: default
  projectIdentifier: infrastructure
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1684507138438
        repoName: rizkidoank/terraform-configs
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
